/**
 * Created by cshampur on 11/4/16.
 */

export const AuthMatrix = {
    'dashboard':                                {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/list':                     {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/remove':                   {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/isolation/create':         {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/isolation/details/view':   {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/isolation/details/edit':   {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/isolation/details/remove': {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/isolation/edit':           {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/bandwidth/create':         {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/bandwidth/details':        {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/bandwidth/edit':           {'DevOps':'y', 'SysAdmin':'y'},
    'networkpolicies/bandwidth/remove':         {'DevOps':'y', 'SysAdmin':'y'},
    'applicationgroups/list':                   {'DevOps':'y', 'SysAdmin':'y'},
    'applicationgroups/remove':                 {'DevOps':'y', 'SysAdmin':'y'},
    'applicationgroups/create':                 {'DevOps':'y', 'SysAdmin':'y'},
    'applicationgroups/details':                {'DevOps':'y', 'SysAdmin':'y'},
    'applicationgroups/details/remove':         {'DevOps':'y', 'SysAdmin':'y'},
    'applicationgroups/edit':                   {'DevOps':'y', 'SysAdmin':'y'},
    'settings/cluster':                         {'DevOps':'y', 'SysAdmin':'y'},
    'settings/networks':                        {'DevOps':'y', 'SysAdmin':'y'},
    'organizations/list':                       {'DevOps':'y', 'SysAdmin':'y'},
    'organizations/remove':                     {'DevOps':'y', 'SysAdmin':'y'},
    'organizations/create':                     {'DevOps':'y', 'SysAdmin':'y'},
    'organizations/details':                    {'DevOps':'y', 'SysAdmin':'y'},
    'networks/list':                            {'DevOps':'y', 'SysAdmin':'n'},
    'networks/remove':                          {'DevOps':'y', 'SysAdmin':'y'},
    'networks/create':                          {'DevOps':'y', 'SysAdmin':'y'},
    'networks/details':                         {'DevOps':'y', 'SysAdmin':'y'},
    'servicelbs/list':                          {'DevOps':'y', 'SysAdmin':'y'},
    'servicelbs/create':                        {'DevOps':'y', 'SysAdmin':'y'},
    'servicelbs/details/edit':                  {'DevOps':'y', 'SysAdmin':'y'},
    'servicelbs/details/view':                  {'DevOps':'y', 'SysAdmin':'y'},
}